### ISSUE TITLE
POD networking is not functioning with this setup

### ISSUE THREAD

**Issue by rockstarartist** [ctienshi/kubernetes-ansible#4]
i attempted an install of this on two baremetal nodes locally, and on 2 vm's on azure on Centos 8.1. Same Issue on both installs.

Pods cant access the api server, pods cant see each other. coredns and kubeproxy are functioning. It almost seems like the pods are trying to get themselves resolved from an upstream DNS server instead of the Kube-DNS server.

Is this an issue you are seeing?

**Comment by jangel97** [comment]
Same happens to me, does anyone know how to solve it?

**Comment by benipeled** [comment]
I see two related issues in this setup:
* **Wrong CIDR for pods**
The cluster initialized with `--pod-network-cidr=172.16.0.0/16` but the default CIDR for flannel CNI is `10.244.0.0/16`, and that of course causes a route mess, which can be handled by adding routes manually but better to avoid it and update the `cidr_v` (env_variables) to `10.244.0.0/16`.

* **Missing ports on FW**
Once `10.244.0.0/16` is used, the pods can communicate with each other but can't communicate with pods running on other nodes, for this you need to allow either `8285/UDP` or `8472/UDP` on each node [0].

But after all that, it seems that something in FW is still blocking DNS queries, and once you turn off FW (`systemctl stop firewalld`) everything works fine - should be investigated on firewalld logs.

[0] https://coreos.com/flannel/docs/latest/troubleshooting.html (Firewalls section)
